stages:
  - build
  - review

include:
  - component: $CI_SERVER_FQDN/Intern/gitlab-ci-components/build-ilias@master
    inputs:
      ilias_image: "srsolutions/ilias:9"
      target_dir: Customizing/global/plugins/Services/Cron/CronHook/SrMemberships
    rules:
      - if: $CI_COMMIT_BRANCH

  - component: $CI_SERVER_FQDN/Intern/gitlab-ci-components/review-ilias@master
    inputs:
      app_name: srmemberships-${CI_COMMIT_REF_SLUG}
    rules:
      - if: $CI_COMMIT_BRANCH